[paths]
telemetry_data_directory="eclss-data/telemetry/yearly-archives"
telemetry_data_directory_splitted="eclss-data/telemetry/partitioned-telemetry"
labels_xls_artifact_uri="minio://eclss-data/ARs - ECLSS - 2022.02.07 - reduced to 2020-2021 v4.xls"
partitioned_telemetry_path="s3://eclss-data/telemetry/partitioned-telemetry/*/*"
minio_model_bucket="eclss-model-bucket"
prod_path="prod-models/eclss-vae/"

[platform]
minio_endpoint="http://minio.minio"
namespace="henrik-steude"

[col-names]
timestamp_col="normalizedTime"
ar_start_ts_col="EVENT GMT (DOY/HH:MM:SS)"
ar_end_ts_col="Duration/End GMT"
ar_col="Anomaly"
ar_symbol_col="SYMBOL"
ar_title_col="TITLE"
ar_id_col="ID"

[images]
split-parquet-file="hsteude/pycon25-scaling-python:v0.2"
dask-component="hsteude/pycon25-scaling-python:v0.3"
dask-worker="hsteude/pycon25-scaling-python:v0.3"
tuning="hsteude/pycon25-scaling-python:v0.4"
training="hsteude/pycon25-scaling-python:v0.4"
evaluation="hsteude/pycon25-scaling-python:v0.4"
serving="hsteude/pycon25-scaling-python:v0.4"
