apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: vae
spec:
  predictor:
    containers:
      - name: pytorch-container
        image: gitlab.kiss.space.unibw-hamburg.de:4567/kiss/code-ml4cps-paper/columbus-ad:commit-a20d7830
        imagePullPolicy: Always
        command:
          - "python"
          - "/app/container_component_src/model_serving.py"
          - "predictor"
        args:
          - --model_name
          - vae
        env:
          - name: STORAGE_URI
            value: "s3://st-bucket/dev-data-01"
          - name: MODEL_FILENAME
            value: "pytorch-job_20240107_170831"

  transformer:
    containers:
      - image: gitlab.kiss.space.unibw-hamburg.de:4567/kiss/code-ml4cps-paper/columbus-ad:commit-a20d7830
        imagePullPolicy: Always
        name: scaler-container
        command:
          - "python"
          - "/app/container_component_src/model_serving.py"
          - "transformer"
        args:
          - --model_name
          - vae
        env:
          - name: STORAGE_URI
            value: "s3://st-bucket/dev-data-01"
          - name: SCALER_FILENAME
            value: "fitted_scaler"
