apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: eclss-point-vae
spec:
  predictor:
    triton:
      storageUri: s3://mlflow-henrik-sebastian-steude/55/dafdc1a936344b1996e5d8160dfc4b96/artifacts/torchscript/model_torchscript.pt
      runtimeVersion: 20.10-py3
      env:
      - name: OMP_NUM_THREADS
        value: "1"
      resources:
        limits:
          nvidia.com/gpu: 1
        requests:
          nvidia.com/gpu: 1
